### PR TITLE
doc: create a README for using the Oracle

### PR DESCRIPTION
**Pull request by alexisji**
A README for the Oracle tool to guide the user.  

Note: when using it i noticed that the ASCII version of PTRAC file seems to be broken and only the binary version works.

### CODE REVIEW

**Comment by arekfu** [comment]
Hi @alexisji, thank you for this PR. Did you see the docs in [`docs/oracle`](https://github.com/arekfu/t4_geom_convert/tree/3203813451534bfa353a116a1b4a1123e8d110a8/docs/oracle)? They end up [in the RTD documentation](https://t4-geom-convert.readthedocs.io/en/latest/oracle/README.html), too. Maybe you could merge the two documents?

**Comment by arekfu** [comment]
Concerning the ASCII version of PTRAC, it may well be broken. I never use it and it's not tested (integration tests use the binary version), but fixing it shouldn't be a big deal. I will open an issue about this.

**Comment by alexisji** [comment]
> Hi @alexisji, thank you for this PR. Did you see the docs in [`docs/oracle`](https://github.com/arekfu/t4_geom_convert/tree/3203813451534bfa353a116a1b4a1123e8d110a8/docs/oracle)? They end up [in the RTD documentation](https://t4-geom-convert.readthedocs.io/en/latest/oracle/README.html), too. Maybe you could merge the two documents?

Hi, 
I'm sorry, i completely missed this part of the `doc` ! 
I'll have a look for merging if there is any missing information in [`docs/oracle`]

**Comment by arekfu** [comment]
@alexisji did you get the chance to check if there is any valuable information to merge into the main document? Thanks!

**Comment by alexisji** [comment]
> @alexisji did you get the chance to check if there is any valuable information to merge into the main document? Thanks!

nope your doc was already great!  
I apologize for that useless PR :)

**Pull request closed without merging**
